//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXApplication5
{
    using System;
    using System.Collections.Generic;
    
    public partial class goods_issue
    {
        public int Id { get; set; }
        public string code { get; set; }
        public Nullable<int> product_id { get; set; }
        public string product_name { get; set; }
        public string product_code { get; set; }
        public Nullable<int> product_quantity { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string note { get; set; }
        public Nullable<int> deleted { get; set; }
    }
}
