//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXApplication5
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public product()
        {
            this.quantity = 0;
            this.deleted = 0;
        }
    
        public int id { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<byte> deleted { get; set; }
    }
}
